name: Random Commit

on:
  schedule:
    - cron: "10 18 * * *"
    # Template: 
    # Time Zone: UTC (+5 hours)
    # minute hour day-of-month month day-of-week
    # 28 11 * * * - every day at 11:28
    # Insert "*" for any value

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run commit script
        run: node commit.js

      - name: Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git push origin HEAD
